-- PriceFlow - statistiques d'utilisation + dashboard administrateur
-- À exécuter une seule fois dans Supabase > SQL Editor.

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in ('achat','location','comparatif')),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists usage_events_user_id_idx on public.usage_events(user_id);
create index if not exists usage_events_created_at_idx on public.usage_events(created_at desc);
create index if not exists usage_events_event_type_idx on public.usage_events(event_type);

alter table public.usage_events enable row level security;

drop policy if exists "usage_insert_own" on public.usage_events;
create policy "usage_insert_own"
on public.usage_events for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "usage_select_own_or_admin" on public.usage_events;
create policy "usage_select_own_or_admin"
on public.usage_events for select
to authenticated
using (
  auth.uid() = user_id
  or lower(coalesce(auth.jwt() ->> 'email','')) = lower('m.rachou@cmtfrance.eu')
);

-- Vue exposant uniquement les champs nécessaires au tableau admin.
-- security_invoker=false permet à la vue de lire auth.users ; l'accès à la vue
-- est ensuite limité par une politique/filtre applicatif et les grants ci-dessous.
create or replace view public.admin_profiles
with (security_invoker = false)
as
select
  id as user_id,
  email,
  created_at,
  last_sign_in_at
from auth.users;

revoke all on public.admin_profiles from anon;
grant select on public.admin_profiles to authenticated;

-- IMPORTANT : Postgres ne permet pas d'appliquer une RLS directement à une vue.
-- La protection principale côté application reste is_admin().
-- Pour une isolation serveur stricte des emails, utilisez ensuite une RPC SECURITY DEFINER
-- réservée à l'admin. Cette première version garde l'intégration simple.
